name: Deploy Loja de Fruta

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Build project
        run: mvn clean install -DskipTests
      - name: Login Docker Hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build docker image
        run: docker build -t jntcruz/demo .
      - name: Push image docker
        run: docker push jntcruz/demo
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: pull image from docker hub
        run: sudo docker pull jntcruz/demo:latest
      - name: Remover docker
        run: docker rm -f demo
      - name: Run docker container
        run: sudo docker run -d -p 8080:8080 --name demo jntcruz/demo